#pragma once
#ifndef __GAME_OBJECT_TYPE__
#define __GAME_OBJECT_TYPE__
enum GameObjectType {
	NONE = -1,
	PLAYER,
	BULLET,
	ENEMY,
	MAP,
	BONUS,
	START_BUTTON,
	RESTART_BUTTON,
	INSTURCTION_BUTTON,
	EXIT_BUTTON,
	MENU_BUTTON,
	NUM_OF_TYPES,
};

#endif /* defined (__GAME_OBJECT_TYPE__)*/