#pragma once
#ifndef __GAME_OBJECT_TYPE__
#define __GAME_OBJECT_TYPE__
enum GameObjectType {
	NONE = -1,
	ISLAND,
	PLAYER,
	CLOUD,
	BULLET,
	ENEMY,
	OCEAN,
	PLANE,
	START_BUTTON,
	RESTART_BUTTON,
	NUM_OF_TYPES,
	MAP,
	INSTURCTION_BUTTON,
	EXIT_BUTTON,
	MENU_BUTTON
};

#endif /* defined (__GAME_OBJECT_TYPE__)*/